### ISSUE TITLE
[Feature Request] <Add a feature that makes you put BetterDiscord Plugins>

### ISSUE THREAD

**Issue by Venus5687** [Vendicated/Vencord#1308]
### Discord Account

LeoTheSmart#7576

### What is it that you'd like to see?

I would absolutely love to see BetterDiscord Plugins compatible with Vencord!

### Request Agreement

- [x] This is not a plugin request

**Comment by Vendicated** [comment]
[Duplicate](https://github.com/Vendicated/Vencord/issues?q=is%3Aissue+betterdiscord+plugins+is%3Aclosed) and not planned. Bd and Vc function in very different ways so this would basically require writing an entire mini-bd inside vencord. I also consider it an anti feature since so many betterdiscord plugins are of very low quality
