### ISSUE TITLE
[Feature Request] VolumeBooster: Support Web/Vesktop

### ISSUE THREAD

**Issue by Darkissou** [Vendicated/Vencord#1944]
### Discord Account
_darkuwu

### What is it that you'd like to see?
I would like to see the VolumeBooster plugin brought to web, I don't see why this wouldn't be a feasible thing so I'm asking. This is probably the only thing holding me back from using Vesktop

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by DTACat** [comment]
i would also love to have this on web coz i desktop has so many bugs so thats why i use vesktop

**Comment by devnyxie** [comment]
I'm quite new to Vencord code (literally started today), but I think I can see that Vesktop has no pre-installed plugins and it's using `vencordDesktopMain.js` from Vencord's latest release in order to get plugins. Since `vencordDesktopMain.js` is minified, it's quite challenging to continue debugging this but I'll continue tomorrow. 🤔

**Comment by Vendicated** [comment]
you can just build from source silly, follow instructions in the source folder and check bottom of vesktop settings

**Comment by devnyxie** [comment]
ah thank you, will do! >_<
It's quite late for me so I'm laggin a bit hehe

**Comment by Ryonez** [comment]
Would love to see an addition of a volume booster, I'm on linux, so the only way to stream is via... well vesktop is the best one for usability. But sadly some folks have very quiet outputs which makes hearing them a struggle at times.

**Comment by ooliver1** [comment]
Does this issue need any assistance or just more people wanting this? Web maxing out at 100% is silly for Discord to do, so this is the only way to boost above 100% for vesktop.

**Comment by Vendicated** [comment]
it needs someone to make it. noone is working on it

**Comment by blaketmdisc** [comment]
Can't you just use a extension to boost the volume?

**Comment by Ryonez** [comment]
> Can't you just use a extension to boost the volume, or does the extensions sound too distorted, idk never used the vc plugin.

There's currently no plugin to boost the vc volume (there is one for BetterDiscord called [BetterVolume](https://github.com/Zerthox/BetterDiscord-Plugins/tree/master/src/BetterVolume)).
As to extensions, Vesktop, the desktop client for Vencord, doesn't support user extensions as far as I'm aware.

This issue here is for the creation of a plugin similar to BetterVolume for Vencord.

**Comment by Nuckyz** [comment]
Implemented as of https://github.com/Vendicated/Vencord/commit/e07a4e19e65b556b0e398a39499b85b88699756b
