### ISSUE TITLE
[vencord.app] fake vencord domain name, possibly malware

### ISSUE THREAD

**Issue by prplwtf** [Vendicated/Vencord#2085]
### Content

I recently stumbled upon the "vencord.app" domain name which might be a typosquatted version of the "vencord.dev". I've decided to add this here due to security concerns.

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by Vendicated** [comment]
hi, thanks for reaching out

we're [well aware](https://vencord.dev/faq/#What-are-the-official-websites-for-Vencord?) of this site and have done everything in our power to undermine this

if you want to help out, you could try reporting this domain to various antimalware companies and maybe have it flagged by them

**Comment by prplwtf** [comment]
@Vendicated I somehow missed that part, sorry. I'll do my part and report them on multiple websites, thanks for your quick response.

**Comment by EpicnessTwo** [comment]
Just going to add to this thread since it seems that I might have downloaded Vencord from this website in the past. Upon re-downloading the installer today, I noticed both .dev and .app in my history for Vencord and did some investigating.

I quickly checked all of the installer binaries that I have, including matching them to each website via date of download and the website actually links to the official Vencord/Installer Github repo on all of the occasions I've used it. I can't be sure it's always been that case but at least for me, the one installer I downloaded via that website (and the currently linked download) seem to be at least legit.

I verified the hash of the downloads just incase and all match those of the official installers so it might not be malware in this case.

Still very odd to stumble upon though!

**Comment by prplwtf** [comment]
Took a peek at their website and they might have changed their mind and used the website to backlink to other (potentionally malicious?) websites.

**Comment by MrDiamondDog** [comment]
> Took a peek at their website and they might have changed their mind and used the website to backlink to other (potentionally malicious?) websites.

Really? I can't find anything that links to a different website

They did update the download page to include "how to download vencord apk"
