### ISSUE TITLE
Disable/Replace MenuBar on QuickCSS

### ISSUE THREAD

**Issue by abUwUser** [Vendicated/Vencord#260]
Discord's MenuBar is being displayed on QuickCSS, even on GNOME. The expected behavior is it for not being shown or for it to be replaced by a custom one.

![image](https://user-images.githubusercontent.com/27961224/204036951-fc1a0d26-ea47-457f-86f0-f3f7d836b237.png)

**Comment by Vendicated** [comment]
I don't think this is possible on web, on desktop it would be possible but it's also kind of useful to have because it's the only way to open devtools in the quick css Editor

**Comment by abUwUser** [comment]
honestly, does it even display on web that menu bar?
anyways, can't you add a keybind for `CTRL` `SHIFT` `I` to open devtools? or include an advanced option on vencord to open devtools on quickcss? or better, open devtools if you hold `SHIFT` when hitting the quickcss button

**Comment by Vendicated** [comment]
it's not that simple

feel free to open a pull request!

**Comment by abUwUser** [comment]
makes sense. thanks!
will leave this issue open tho if somebody is willing to try

**Comment by Vendicated** [comment]
Implemented in https://github.com/Vendicated/Vencord/commit/5e97cc0fc366acc268665c359a35e7c085364576 for Discord Desktop
The bar is still shown on Web because modern browsers don't allow you to hide the bar for security reasons (If you could hide the address bar, it would be very easy to embed something like a fake paypal popup and steal your paypal login info)
