### ISSUE TITLE
[Minor bug] "Plugins that require a restart" notice at above of plugins page when toggling a plugin does not persist upon closing/reopening

### ISSUE THREAD

**Issue by aloshTM** [Vendicated/Vencord#2760]
### Discord Account

ayelosh

### What happens when the bug or crash occurs?

When toggling a plugin, the notice for "This plugin requires a restart" does not persist if you close and reopen the plugins page. This could be an issue if a person toggled a plugin on accident and didn't know about it

### What is the expected behaviour?

The notice should persist

### How do you recreate this bug or crash?

1. Go to Vencord Plugins menu
2. Toggle a plugin
3. Observe the notice being there
4. Close the Settings page, dismiss the popup, and reopen the Settings page to the Vencord Plugins menu
5. Observe the popup no longer being there
6. Profit

### Errors

```
N/A
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by surgedevs** [comment]
This happens because Vencord gives you a warning before you leave the plugin page:
![image](https://github.com/user-attachments/assets/68cb354e-2c4e-47f4-a23d-e2e264b195d7)

Furthermore I have not yet seen you report these in the Vencord Discord server. Please read the requirements for opening issues:
![image](https://github.com/user-attachments/assets/edc49be2-41b1-4c63-b8e3-c0f971c30ac0)

**Comment by aloshTM** [comment]
q
