### ISSUE TITLE
petpet dosen't work

### ISSUE THREAD

**Issue by isatsou** [Vendicated/Vencord#2933]
### Discord Account

isatsou_01682

### What happens when the bug or crash occurs?

when i run petpet

### What is the expected behaviour?

pet

### How do you recreate this bug or crash?

run petpet

### Errors

```
[object Event]
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well
- [X] I have read the requirements for opening an issue above

**Comment by Sqaaakoi** [comment]
It's been discovered in the support channel to be a CORS issue, only some users are experiencing this, see https://canary.discord.com/channels/1015060230222131221/1026515880080842772/1292438826446360586
 ![image](https://github.com/user-attachments/assets/dc54041c-c1ca-4dee-93f7-b9312f5d04e4)


EmoteCloner also is broken due to CORS for some users too

**Comment by Vendicated** [comment]
this is a discord issue.
