### ISSUE TITLE
requires macOS 12

### ISSUE THREAD

**Issue by jkrosado** [Vendicated/Vencord#331]
i currently run macOS 10.15 and am unable to update. is it possible to run it in 10.15?

**Comment by MeguminSama** [comment]
Vencord is OS-agnostic and should run on anything that runs Discord. Your issue needs more information. Are you talking about the GUI installer? In which case this issue should be placed in the https://github.com/Vendicated/VencordInstaller repo instead.

If you're getting error logs, please post them along with any screenshots and other relevant information.

**Comment by ArjixWasTaken** [comment]
If discord runs, then vencord should also run.

What does not "run"?
We can't read your mind, and we also don't have access to your computer.

You have to give more info, does discord crash? Does vencord just not do anything? What exactly is the issue?

Since you mentioned the OS version, I assume this has to do with either the vencord installer, or an npm package that has a minimum required MacOS version.

We really can't help if you don't give info.
Do you have any error messages to show?
Have you opened the dev tools? Can you even open the dev tools? Can you see errors in the dev tools console?

**Comment by ArjixWasTaken** [comment]
I gave some example questions that you may want to answer.

**Comment by Vendicated** [comment]
What exactly is the issue? Please provide more info within the next week or we'll have to close this issue
