### ISSUE TITLE
prettier and eslint rules

### ISSUE THREAD

**Issue by adryd325** [Vendicated/Vencord#45]
prettier and eslint rules would help keep code styling consistent without much thought from extension developers.

**Comment by MeguminSama** [comment]
<a:catnod:740290415961571338>

**Comment by taskylizard** [comment]
use the editorconfig config

**Comment by MeguminSama** [comment]
editorconfig isn't very strict :>

**Comment by Vendicated** [comment]
I personally really dislike prettier because it is way too opiniated, imo produces ugly code and doesn't let you do your own style. That's why I chose the VsCode formatter with .editorconfig, because it adapts to the existing code and gives you more freedom, I just wish it supported more rules ;-; 

I think eslint can be used for this purpose as well (?), I just honestly couldn't be bothered to configure it and I dislike the defaults. I'll look into it tomorrow

**Comment by adryd325** [comment]
i think eslint has some options for requiring types and stuff too, helpful for people just starting with typescript

**Comment by Vendicated** [comment]
I added an eslint config now, thanks for the suggestion! (https://github.com/Vendicated/Vencord/blob/main/.eslintrc.json)

I don't know eslint too well so maybe there's more rules that should be added. If so, just feel free to suggest them
I avoided the "recommended" config because I dislike some of its rules like ban-var (var is useful to hoist variables from try / if blocks)
