### ISSUE TITLE
[Feature Request] Winget package

### ISSUE THREAD

**Issue by alexandreteles** [Vendicated/Vencord#484]
### Discord Account

afterSt0rm#0740

### What is it that you'd like to see?

I recently upgraded my PC, and I'm doing the "install everything again" step, which is painful. Most of my applications are easily available using winget, so it would be nice to have the Vencord installer also available on winget. You can find additional information about how to create a winget package here: https://github.com/microsoft/winget-create

It also helps that once you update the package version, I can upgrade the Vencord installer automatically, together with my other applications.

Thank you!

### Request Agreement

- [X] This is not a plugin request

**Comment by Sculas** [comment]
This is *almost* possible, the CLI just needs to add a "channel" flag so you can select which Discord channel should be patched.

**Comment by Spacellary** [comment]
That's great for new install, I'll probably be doing a few soon on my end. To add to it, maybe it could be added as a Scoop.sh package, or maybe even Chocolatey. It's easy to have a script that installs and upgrades everything without the chore of dealing with multiple UACs or prompts, and Vencord could be a perfect addition to that script.

**Comment by Vendicated** [comment]
i don't think this is something I'm interested in doing since I don't think it's very useful and just adds more things I need to maintain, not to mention once there's a winget package, people will also ask for a scoop package, a deb, an aur package, and so on. The installer is something you usually will only need to use once anyway so I don't really see the point and if you really find it that much of a chore you could write a simple powershell script to do it for u! 

I'm pretty sure winget and similar allow unofficial packages though, so feel free to do that (and pull request any changes to the installer that are necessary (and reasonable))
