### ISSUE TITLE
[Bug] Custom CSS & Themes do not work on Firefox

### ISSUE THREAD

**Issue by muznyo** [Vendicated/Vencord#548]
### What happens when the bug or crash occurs?

I use a vencord firefox extension and i have issues with it.
When putting the css link, it shows:

 `Error: NetworkError when attempting to fetch resource.`

It shows with any BetterDiscord Theme

### What is the expected behaviour?

It applies the theme without any problems

### How do you recreate this bug or crash?

1. open discord settings
2. click on themes in vencord section
3. put in a css link
4. the error shows up

### Errors

```
Replace this text with your crash-log.
```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by lewisakura** [comment]
Firefox CSP issue, nothing to fix here

**Comment by Vendicated** [comment]
as mentioned by lewi, Firefox has a bug that makes it not correctly apply our networking rules which makes it impossible for Vencord to load custom themes. This is an issue with Firefox and needs to be fixed by Firefox, not us

Solutions:
- Use Discord desktop or Discord on a Chromium based Browser
- You can still set custom css via the console: `await VencordNative.ipc.invoke("VencordSetQuickCss", THE_CSS_TEXT_AS_STRING_HERE)`

**Comment by Vendicated** [comment]
Okay I just found out the reason is because Firefox manifest v3 implementation is just super bad and they didn't implement many apis auch as the declarativeNetRequest api that Vencord depends on (https://bugzilla.mozilla.org/show_bug.cgi?id=1687755). So we just need to add back legacy request interception

**Comment by muznyo** [comment]
> Okay I just found out the reason is because Firefox manifest v3 implementation is just super bad and they didn't implement many apis auch as the declarativeNetRequest api that Vencord depends on (https://bugzilla.mozilla.org/show_bug.cgi?id=1687755). So we just need to add back legacy request interception

interesting

so it will be able to work again?

**Comment by Vendicated** [comment]
I tried fixing it in https://github.com/Vendicated/Vencord/pull/554 but it simply doesn't work because reasons:tm: and I will not put any more effort into trying to write ugly workarounds for problems that shouldn't exist

So unless someone else fixes it, it will likely stay broken

**Comment by muznyo** [comment]
The workaround i used is that i installed this [extension](https://addons.mozilla.org/en-US/firefox/addon/styl-us/) and copied css theme in there

**Comment by NSPC911** [comment]
I would just recommend getting Tampermonkey and downloading the userscripts. I don't have any problems with it, so it should be fine. I don't know about other userscript managers like greasemonkey, violentmonkey and firemonkey, but it may have problems

**Comment by Vendicated** [comment]
Fixed in https://github.com/Vendicated/Vencord/commit/5305447f442b57443c4616ccd8d530c2c5e539b4!!

Keeping this open until the update reaches the firefox store

**Comment by Vendicated** [comment]
Fix landed in 1.1.9!

**Comment by muznyo** [comment]
Still doesn't work, has same error message like before

**Comment by Vendicated** [comment]
> Still doesn't work, has same error message like before

Update the extension to the latest version.

**Comment by muznyo** [comment]
> > Still doesn't work, has same error message like before
> 
> Update the extension to the latest version.

It's 1.1.9, right?

If yes, i already have it

**Comment by Vendicated** [comment]
please use our support channel then

**Comment by muznyo** [comment]
Nevermind, it works now after a few reopenings
