### ISSUE TITLE
FakeNitro theme resseting when switching to another account

### ISSUE THREAD

**Issue by averagenokiauser** [Vendicated/Vencord#671]
### Discord Account

LenartNotFound#8228

### What happens when the bug or crash occurs?

on my main account i use fakenitro theme but when i switch to my second account and then back to the main one that theme resets and i need to select it again

### What is the expected behaviour?

it should not reset the theme

### How do you recreate this bug or crash?

select any built in theme in discord that you can use if you have fake nitro plugin enabled

then you switch to your second account

when you switch back to your main account the theme will be reset.

### Errors

```

```

### Request Agreement

- [X] I am using Discord Stable or tried on Stable and this bug happens there as well

**Comment by somerandomcloud** [comment]
Not an issue with vencord, chances are this happens even with nitro accounts... Plus is it even that big of a deal

**Comment by Vendicated** [comment]
yes

**Comment by averagenokiauser** [comment]
> I think you understood this wrong @Vendicated, the person meant if you go _back_ to your account, it should have the old set theme. But I don't think this works because you can't store it on the servers of Discord, right?

yes i meant that

**Comment by skaffi** [comment]
I was having this issue constantly, to much frustration, despite not even using one of the FakeNitro themes. I simply wanted to use the default Light theme, and have it stick to it.

When I realised the FakeNitro plugin was causing the issue, I disabled it, and the issue ceased completely.

I had FakeNitro enabled because of some of the other benefits (mainly streaming in higher quality, but the emoji and sticker stuff is nifty too), but I had to say goodbye to those things, because of a bug with a part of the plugin I wasn't using - that's a bummer.

If the issue is unavoidable, might I instead suggest that you spin the theme part of the FakeNitro plugin out into its own, separate plugin - you might call it, say, FakeNitroThemes? Then at least the issue will be better contained, and only people who want to use fake Nitro themes specifically will have to make the tradeoff, while people who just want to stream in higher quality, or send custom emoji or stickers won't have to suffer having their default theme reset itself all the time.
